FROM golang:alpine as builder
WORKDIR /build
COPY . .
RUN apk add git build-base gcc
RUN go build -o users

FROM alpine
WORKDIR /app
COPY --from=builder /build/users .
ENV app_env=release
ENV GIN_MODE=release
CMD ["./users"]